name: test

on:
  push:
    paths:
      - ofdm-simulation/**
      - .github/**
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: docker-ofdm-simulation
          tags: |
            type=semver,pattern={{raw}} # tag を利用
            type=sha,format=short       # sha を利用

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha
      - name: Run pytest
        run: docker run -v .:/app ${{ steps.metadata.outputs.tags }} pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: docker-ofdm-simulation
          tags: |
            type=semver,pattern={{raw}} # tag を利用
            type=sha,format=short       # sha を利用

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha
      - name: mypy
        run: docker run -v .:/app ${{ steps.metadata.outputs.tags }} mypy --strict .