name: test

on:
  push:
    paths:
      - ofdm-simulation/**
      - .github/**
defaults:
  run:
    working-directory: ofdm-simulation
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: docker-ofdm-simulation
          tags: |
            type=semver,pattern={{raw}} # tag を利用
            type=sha,format=short       # sha を利用

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          context: ofdm-simulation
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max # 全レイヤーキャッシュ
          cache-to: type=local
      - name: Run test
        run: docker run ${{ steps.metadata.outputs.tags }} pytest