name: test

on:
  push:
    paths:
      - ofdm-simulation/**
      - .github/**
jobs:
  pytest:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - uses: actions/checkout@v4
      - name: cache pytest environment
        id: cache-pytest
        uses: actions/cache@v4
        with:
          path: cache-pytest
          key: ${{ runner.os }}-cache-pytest
      - name: setup
        if: steps.cache-pytest.outputs.cache-hit != 'true'
        run: |
          apt-get update && apt-get install -y octave octave-signal python3 python3-pip
          pip install -r ofdm-simulation/requirements.txt --break-system-packages
      - name: Run test
        run: pytest ofdm-simulation/