name: test

on:
  push:
    # paths:
      # - ofdm-simulation/**
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: install octave
        run: apt-get update && apt-get install -y octave octave-signal
      - name: pip
        uses: actions/checkout@v4
        uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Run test
        run: pytest ofdm-simulation/