name: test

on:
  push:
    paths:
      - ofdm-simulation/**
jobs:
  pytest:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install require packages
        run: apt-get update && apt-get install -y python3 python3-pip octave octave-signal && pip install -r ofdm-simulation/requirements.txt
      - uses: actions/checkout@v4
      - name: Run test
        run: pytest ofdm-simulation/