name: test

on:
  push:
    # paths:
      # - ofdm-simulation/**
jobs:
  pytest:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: apt-get update && apt-get install -y octave octave-signal python3 python3-pip
      - name: setup pip
        run: pip install -r ofdm-simulation/requirements.txt --break-system-packages
      - name: Run test
        run: pytest ofdm-simulation/